log:
  level: DEBUG

api:
  dashboard: false
  insecure: true

entryPoints:
  web:
   address: ":81"



providers:
  file:
    filename: dynamic.yaml




experimental:
  
  localPlugins:
    traefikapim:
      moduleName: github.com/yasahmed/traefikapim

